services:
    app:
      build: .
      ports:
        - "8001:8000"  # App now listens on 8001 externally, 8000 internally
      volumes:
        - .:/app

    nginx:
      image: nginx:latest
      ports:
        - "8000:80"  # Nginx listens on 8000, proxies to app
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./logs:/var/log/nginx
      depends_on:
        - app
