services:
    app:
      build: .
      volumes:
        - .:/app
      environment:
        - UVICORN_WORKERS=2  # Optional: Run multiple workers per container
      deploy:
        replicas: 3  # Run 3 instances of the app

    nginx:
      image: nginx:latest
      ports:
        - "8000:80"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./logs:/var/log/nginx
      depends_on:
        - app
